darkube_build_arvan-challenge_mostafa-rastegar_hamravesh-c13:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  interruptible: true
  only:
    refs:
      - develop
  script:
    - IMAGE_ADDRESS="registry.hamdocker.ir/mostafa-rastegar/arvan-challenge"
    - "darkube build --push -t $IMAGE_ADDRESS:$CI_COMMIT_SHORT_SHA -t $IMAGE_ADDRESS:$CI_COMMIT_REF_SLUG
      --workdir . --file ./Dockerfile --build-context . "
  stage: build
darkube_deploy_arvan-challenge_mostafa-rastegar_hamravesh-c13:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  interruptible: true
  only:
    refs:
      - develop
  script:
    - darkube deploy --token ${DEPLOY_TOKEN_ARVAN_CHALLENGE_MOSTAFA_RASTEGAR_HAMRAVESH_C13}
      --app-id ${APP_ID_ARVAN_CHALLENGE_MOSTAFA_RASTEGAR_HAMRAVESH_C13} --image-tag
      ${CI_COMMIT_SHORT_SHA} --job-id ${CI_JOB_ID}
  stage: deploy
