const types = {
  GET_ARTICLES: "GET_ARTICLES",
  GET_ARTICLES_SLUG: "GET_ARTICLES_SLUG",
  POST_ARTICLES: "POST_ARTICLES",
  PUT_ARTICLES_SLUG: "PUT_ARTICLES_SLUG",
  DELETE_ARTICLES_SLUG: "DELETE_ARTICLES_SLUG",
  GET_TAGS: "GET_TAGS",
};

export default types;
